# -*- coding: utf-8 -*-
"""Rasa_PFWChatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TWqJFHa-EXItgd5qApJc0mnytCXw7tLv

**Rasa is Opensource Machine Learning framework used for developing AI based chatbot.**
"""

!pip install rasa==3.4.5

!pip install -U tables

!pip install tzlocal==2.1
!pip install jedi==0.11
!pip install pluggy==0.6
!pip install prompt-toolkit==2.0.10
!pip install websockets==10.2
!pip install websocket-client

!pip install -U ipython

# !python -m spacy download en
!python -m spacy download en_core_web_sm

!pip install nest_asyncio

import os
import rasa
import nest_asyncio

nest_asyncio.apply()
print("Event loop ready.")

from rasa.cli.scaffold import create_initial_project

project = "PFW Chatbot"
create_initial_project(project)

# move into project directory and show files
os.chdir(project)
print(os.listdir("."))

# Commented out IPython magic to ensure Python compatibility.
# # from dataclasses import make_dataclass
# %%writefile data/nlu.yml
# version: "3.1"
# 
# nlu:
# 
# - intent: greet
#   examples: |
#     - hey
#     - hello
#     - hi
#     - hello there
#     - good morning
#     - good evening
#     - moin
#     - hey there
#     - lets go
#     - hey dude
#     - goodmorning
#     - goodevening
#     - good afternoon
# 
# - intent: goodbye
#   examples: |
#     - cu
#     - good by
#     - cee you later
#     - good night
#     - bye
#     - goodbye
#     - have a nice day
#     - see you around
#     - bye bye
#     - see you later
# 
# - intent: affirm
#   examples: |
#     - yes
#     - y
#     - indeed
#     - of course
#     - that sounds good
#     - correct
# 
# - intent: deny
#   examples: |
#     - no
#     - n
#     - never
#     - I dont think so
#     - dont like that
#     - no way
#     - not really
# 
# - intent: mood_great
#   examples: |
#     - perfect
#     - great
#     - amazing
#     - feeling like a king
#     - wonderful
#     - I am feeling very good
#     - I am great
#     - I am amazing
#     - I am going to save the world
#     - super stoked
#     - extremely good
#     - so so perfect
#     - so good
#     - so perfect
# 
# - intent: mood_unhappy
#   examples: |
#     - my day was horrible
#     - I am sad
#     - I dont feel very well
#     - I am disappointed
#     - super sad
#     - Im so sad
#     - sad
#     - very sad
#     - unhappy
#     - not good
#     - not very good
#     - extremly sad
#     - so saad
#     - so sad
# 
# - intent: bot_challenge
#   examples: |
#     - are you a bot?
#     - are you a human?
#     - am I talking to a bot?
#     - am I talking to a human?
# 
# - intent: ask_graduation
#   examples: |
#     - I THINK IM READY TO GRADUATE. WHAT DO I DO NOW?
#     - What should I do to graduate?
#     - How can I apply for graduation?
#     - Tell me the process to graduate.
# 
# - intent: credit_hours_needed
#   examples: |
#     - How many credit hours do I need to earn my degree?
#     - Whats the minimum credit requirement for a degree?
#     - Tell me about the credit hours needed for graduation.
# 
# - intent: next_steps
#   examples: |
#     - I am close or have finished my degree requirements, what do I do now?
#     - What are the next steps after completing degree requirements?
#     - Can you guide me on the post-degree requirements?
# 
# - intent: graduation_application
#   examples: |
#     - What does “applying for graduation” mean exactly?
#     - Explain the purpose of applying for graduation.
#     - Why should I fill out a graduation application?
# 
# - intent: degree_on_transcript
#   examples: |
#     - When will my degree show on my transcript?
#     - How long does it take for the degree to appear on my transcript?
#     - Can you tell me about the transcript update after graduation?
# 
# - intent: application_deadline
#   examples: |
#     - When should I apply for graduation?
#     - What are the deadlines for graduation applications?
#     - How early do I need to apply for graduation?
# 
# - intent: missed_deadline
#   examples: |
#     - I missed the deadline to apply for graduation, now what do I do?
#     - What should I do if Ive missed the graduation application deadline?
#     - Can I still apply for graduation after the deadline?
# 
# - intent: graduation_vs_commencement
#   examples: |
#     - What is the difference between graduation and commencement?
#     - Explain the distinction between graduation and commencement.
#     - When does one officially graduate?
# 
# - intent: more_information
#   examples: |
#     - How do I find out more information about commencement?
#     - Tell me where I can get more details about the commencement ceremony.
#     - Where can I find additional information about graduation?
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile domain.yml
# version: "3.1"
# 
# intents:
#   - greet
#   - goodbye
#   - affirm
#   - deny
#   - mood_great
#   - mood_unhappy
#   - bot_challenge
#   - ask_graduation
#   - credit_hours_needed
#   - next_steps
#   - graduation_application
#   - degree_on_transcript
#   - application_deadline
#   - missed_deadline
#   - graduation_vs_commencement
#   - more_information
# 
# responses:
#   utter_greet:
#   - text: "Hey! How are you?"
# 
#   utter_cheer_up:
#   - text: "Here is something to cheer you up:"
#     image: "https://i.imgur.com/nGF1K8f.jpg"
# 
#   utter_did_that_help:
#   - text: "Did that help you?"
# 
#   utter_happy:
#   - text: "Great, carry on!"
# 
#   utter_goodbye:
#   - text: "Bye"
# 
#   utter_iamabot:
#   - text: "I am a bot, powered by Rasa."
# 
#   utter_ask_graduation:
#   - text: "To be considered for graduation from a Purdue Fort Wayne program, you must submit an application for graduation. By submitting this application, you are formally requesting that your academic record be audited for graduation in the specified semester. If you do not apply for graduation, this audit will not be conducted and you cannot have a degree awarded."
# 
#   utter_credit_hours_needed:
#   - text: "For completion of undergraduate plans of study of at least 60 credits, associate degrees may be conferred. For completion of undergraduate plans of study of at least 120 credits, bachelor’s degrees may be conferred. These are minimum standards set by the University. Departments may impose stricter requirements, check your online degree audit or contact your academic advisor for specific requirements."
# 
#   utter_next_steps:
#   - text: "Apply for graduation by completing the application for graduation. This application is necessary even if you do not plan to take part in commencement. Purdue Fort Wayne relies on the application for graduation to know the semester you intend to complete degree requirements. If you’re pursuing multiple degrees and/or certificates, you should indicate all anticipated degrees and certificates on your application for graduation."
# 
#   utter_graduation_application:
#   - text: "Here is what the application for graduation does:\n\n- Triggers the graduation audit process\n- Ensures that you receive commencement information\n- Allows the university to order your diploma"
# 
#   utter_degree_on_transcript:
#   - text: "Degrees are generally posted within 30 days of the close of the semester of graduation."
# 
#   utter_application_deadline:
#   - text: "Submitting your application for graduation at least the semester prior to your anticipated completion is required. The deadlines to apply for graduation are:\n\n- Fall Semester: June 1\n- Spring Semester: November 1\n- Summer Session II: February 1\n\nIf the graduation application deadline has passed, apply immediately. If you do not apply for graduation by the deadline, there may be a delay in posting your degree to your transcript and receipt of your diploma, and for commencement purposes, you may not be considered for honors, and your name may not appear in the program."
# 
#   utter_missed_deadline:
#   - text: "If you have questions about the deadline to apply for graduation, email graduation@pfw.edu. If you have missed the deadline to apply for graduation, you may need to apply for the next available graduation date."
# 
#   utter_graduation_vs_commencement:
#   - text: "Graduation refers to the date you completed your degree requirements, which is your degree conferral. Commencement is the ceremony celebrating all the students who have graduated or anticipate graduating within this academic year."
# 
#   utter_more_information:
#   - text: "Commencement is overseen by the Communications and Marketing Department. Look at the website: www.pfw.edu/commencement for more information. If you cant find the answers to your questions on the website, email the Communications and Marketing Department at marketing@pfw.edu."
# 
# session_config:
#   session_expiration_time: 60
#   carry_over_slots_to_new_session: true
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile data/stories.yml
# version: "3.1"
# 
# stories:
# 
# - story: happy path
#   steps:
#   - intent: greet
#   - action: utter_greet
#   - intent: mood_great
#   - action: utter_happy
# 
# - story: sad path 1
#   steps:
#   - intent: greet
#   - action: utter_greet
#   - intent: mood_unhappy
#   - action: utter_cheer_up
#   - action: utter_did_that_help
#   - intent: affirm
#   - action: utter_happy
# 
# - story: sad path 2
#   steps:
#   - intent: greet
#   - action: utter_greet
#   - intent: mood_unhappy
#   - action: utter_cheer_up
#   - action: utter_did_that_help
#   - intent: deny
#   - action: utter_goodbye
# 
# - story: User asks about graduation process
#   steps:
#   - intent: ask_graduation
#   - action: utter_ask_graduation
# 
# - story: User inquires about credit hours needed
#   steps:
#   - intent: credit_hours_needed
#   - action: utter_credit_hours_needed
# 
# - story: User asks about next steps after completing degree requirements
#   steps:
#   - intent: next_steps
#   - action: utter_next_steps
# 
# - story: User seeks clarification on graduation application
#   steps:
#   - intent: graduation_application
#   - action: utter_graduation_application
# 
# - story: User wants to know when the degree appears on the transcript
#   steps:
#   - intent: degree_on_transcript
#   - action: utter_degree_on_transcript
# 
# - story: User asks about graduation application deadlines
#   steps:
#   - intent: application_deadline
#   - action: utter_application_deadline
# 
# - story: User missed the graduation application deadline
#   steps:
#   - intent: missed_deadline
#   - action: utter_missed_deadline
# 
# - story: User inquires about the difference between graduation and commencement
#   steps:
#   - intent: graduation_vs_commencement
#   - action: utter_graduation_vs_commencement
# 
# - story: User asks for more information about commencement
#   steps:
#   - intent: more_information
#   - action: utter_more_information
# 
#

config = "config.yml"
training_files = "data/"
domain = "domain.yml"
output = "models/"
print(config, training_files, domain, output)

model_path = rasa.train(domain, config, [training_files], output)
print(model_path)

from rasa.jupyter import chat

endpoints =None #'endpoints.yml'

chat(model_path.model, endpoints)

! rasa test

# # import rasa.data as data
# from rasa.nlu import nlu_data_directory
# from rasa.

# stories_directory, nlu_data_directory = get_core_nlu_directories(training_files)

# print(stories_directory, nlu_data_directory)

# rasa.test(model_path, stories_directory, nlu_data_directory)

# print("Done testing...")